name = input("what is your name?")
country = input("where are your from?")
town = input("Where do you live?")
Siblings = input("How many siblings do you have?")
Movie = input("What is your favourite Movie?")
age = input("what is your age?")
food = input("what is your favourite food?")
colour = input("what is your favourite colour?")
videoGame = input("what is your favourite video game??")
sport = input("what is your favourite football club?")
print("Name:"+ age + " Background:" + country + " town:" + " no of siblings" + Siblings + " Favourite movie:" + Movie + " age:" + age + " favourite food:" + food + " favourite color:" + colour + " favourite video game:" + videoGame + "favourite sport:" + sport)